# Generated by Django 3.2 on 2021-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
